/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ToursIndexImport } from './routes/tours/index'
import { Route as BlogsIndexImport } from './routes/blogs/index'
import { Route as ToursTourIdImport } from './routes/tours/$tourId'
import { Route as BlogsBlogIdImport } from './routes/blogs/$blogId'

// Create/Update Routes

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToursIndexRoute = ToursIndexImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsIndexRoute = BlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRoute,
} as any)

const ToursTourIdRoute = ToursTourIdImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRoute,
} as any)

const BlogsBlogIdRoute = BlogsBlogIdImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdImport
      parentRoute: typeof rootRoute
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdImport
      parentRoute: typeof rootRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/tours': typeof ToursIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/tours': typeof ToursIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/tours/': typeof ToursIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$blogId'
    | '/tours/$tourId'
    | '/blogs'
    | '/tours'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$blogId'
    | '/tours/$tourId'
    | '/blogs'
    | '/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$blogId'
    | '/tours/$tourId'
    | '/blogs/'
    | '/tours/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  ToursTourIdRoute: typeof ToursTourIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  ToursTourIdRoute: ToursTourIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/blogs/$blogId",
        "/tours/$tourId",
        "/blogs/",
        "/tours/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/blogs/$blogId": {
      "filePath": "blogs/$blogId.tsx"
    },
    "/tours/$tourId": {
      "filePath": "tours/$tourId.tsx"
    },
    "/blogs/": {
      "filePath": "blogs/index.tsx"
    },
    "/tours/": {
      "filePath": "tours/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
